# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerApp/server_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 50, 511, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageRawLab = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.imageRawLab.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.imageRawLab.setText("")
        self.imageRawLab.setScaledContents(False)
        self.imageRawLab.setObjectName("imageRawLab")
        self.horizontalLayout.addWidget(self.imageRawLab)
        self.imageDetectLab = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.imageDetectLab.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.imageDetectLab.setText("")
        self.imageDetectLab.setScaledContents(False)
        self.imageDetectLab.setObjectName("imageDetectLab")
        self.horizontalLayout.addWidget(self.imageDetectLab)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(210, 10, 271, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connectBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.connectBut.setObjectName("connectBut")
        self.horizontalLayout_2.addWidget(self.connectBut)
        self.disconnectBut = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.disconnectBut.setObjectName("disconnectBut")
        self.horizontalLayout_2.addWidget(self.disconnectBut)
        self.connectedList = QtWidgets.QListView(self.centralwidget)
        self.connectedList.setGeometry(QtCore.QRect(50, 330, 171, 192))
        self.connectedList.setObjectName("connectedList")
        self.chatTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.chatTextEdit.setGeometry(QtCore.QRect(230, 330, 421, 191))
        self.chatTextEdit.setObjectName("chatTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 310, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 310, 61, 16))
        self.label_2.setObjectName("label_2")
        self.sendLine = QtWidgets.QLineEdit(self.centralwidget)
        self.sendLine.setGeometry(QtCore.QRect(230, 530, 341, 20))
        self.sendLine.setObjectName("sendLine")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(580, 530, 75, 23))
        self.sendButton.setObjectName("sendButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectBut.setText(_translate("MainWindow", "Khởi động"))
        self.disconnectBut.setText(_translate("MainWindow", "Ngắt kết nối"))
        self.label.setText(_translate("MainWindow", "Danh sách kết nôi"))
        self.label_2.setText(_translate("MainWindow", "Trò chuyện"))
        self.sendButton.setText(_translate("MainWindow", "Gửi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
